project:
  name: connect-integration-aspect-wfm
  owner: support@aspect.com
  package_lambda: false
  regions:
  - us-east-1
  s3_bucket: 'quickstart-reference-dburkhead'
tests:
  default:
    parameters:
      KdaApplicationName: tcat-$[taskcat_random-string]
      ConnectS3Bucket: tcat-$[taskcat_random-string]
      ConnectS3Prefix: tcat-$[taskcat_random-string]/
      ConnectS3KmsArn: ''
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
    - us-east-1
    s3_bucket: 'quickstart-reference-dburkhead'
    template: templates/aspect-wfm-ap-kda-create-stream.template.yaml
