---
AWSTemplateFormatVersion: '2010-09-09'
Description: Helper template to create a Kinesis stream (qs-1s0oq6gum)
Resources:
  KinesisStream:
   Type: AWS::Kinesis::Stream
   Properties:
    RetentionPeriodHours: 24
    ShardCount: 1
Outputs:
  KinesisStreamArn:
    Value: !GetAtt KinesisStream.Arn
...
